//go:build !ignore_autogenerated

/*

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigError) DeepCopyInto(out *ConfigError) {
	_ = "STUB: not implemented"

	// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigError.
	return
}

func (in *ConfigError) DeepCopy() *ConfigError { _ = "STUB: not implemented"; return nil }

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigPodStatus) DeepCopyInto(out *ConfigPodStatus) { _ = "STUB: not implemented"; return }

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigPodStatus.
func (in *ConfigPodStatus) DeepCopy() *ConfigPodStatus { _ = "STUB: not implemented"; return nil }

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConfigPodStatus) DeepCopyObject() runtime.Object {
	_ = "STUB: not implemented"
	return *new(runtime.Object)
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigPodStatusList) DeepCopyInto(out *ConfigPodStatusList) {
	_ = "STUB: not implemented"
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigPodStatusList.
func (in *ConfigPodStatusList) DeepCopy() *ConfigPodStatusList {
	_ = "STUB: not implemented"
	return nil
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConfigPodStatusList) DeepCopyObject() runtime.Object {
	_ = "STUB: not implemented"
	return *new(runtime.Object)
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigPodStatusStatus) DeepCopyInto(out *ConfigPodStatusStatus) {
	_ = "STUB: not implemented"
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigPodStatusStatus.
func (in *ConfigPodStatusStatus) DeepCopy() *ConfigPodStatusStatus {
	_ = "STUB: not implemented"
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConstraintPodStatus) DeepCopyInto(out *ConstraintPodStatus) {
	_ = "STUB: not implemented"
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConstraintPodStatus.
func (in *ConstraintPodStatus) DeepCopy() *ConstraintPodStatus {
	_ = "STUB: not implemented"
	return nil
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConstraintPodStatus) DeepCopyObject() runtime.Object {
	_ = "STUB: not implemented"
	return *new(runtime.Object)
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConstraintPodStatusList) DeepCopyInto(out *ConstraintPodStatusList) {
	_ = "STUB: not implemented"
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConstraintPodStatusList.
func (in *ConstraintPodStatusList) DeepCopy() *ConstraintPodStatusList {
	_ = "STUB: not implemented"
	return nil
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConstraintPodStatusList) DeepCopyObject() runtime.Object {
	_ = "STUB: not implemented"
	return *new(runtime.Object)
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConstraintPodStatusStatus) DeepCopyInto(out *ConstraintPodStatusStatus) {
	_ = "STUB: not implemented"
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConstraintPodStatusStatus.
func (in *ConstraintPodStatusStatus) DeepCopy() *ConstraintPodStatusStatus {
	_ = "STUB: not implemented"
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConstraintTemplatePodStatus) DeepCopyInto(out *ConstraintTemplatePodStatus) {
	_ = "STUB: not implemented"
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConstraintTemplatePodStatus.
func (in *ConstraintTemplatePodStatus) DeepCopy() *ConstraintTemplatePodStatus {
	_ = "STUB: not implemented"
	return nil
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConstraintTemplatePodStatus) DeepCopyObject() runtime.Object {
	_ = "STUB: not implemented"
	return *new(runtime.Object)
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConstraintTemplatePodStatusList) DeepCopyInto(out *ConstraintTemplatePodStatusList) {
	_ = "STUB: not implemented"
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConstraintTemplatePodStatusList.
func (in *ConstraintTemplatePodStatusList) DeepCopy() *ConstraintTemplatePodStatusList {
	_ = "STUB: not implemented"
	return nil
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConstraintTemplatePodStatusList) DeepCopyObject() runtime.Object {
	_ = "STUB: not implemented"
	return *new(runtime.Object)
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConstraintTemplatePodStatusStatus) DeepCopyInto(out *ConstraintTemplatePodStatusStatus) {
	_ = "STUB: not implemented"
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConstraintTemplatePodStatusStatus.
func (in *ConstraintTemplatePodStatusStatus) DeepCopy() *ConstraintTemplatePodStatusStatus {
	_ = "STUB: not implemented"
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnforcementPointStatus) DeepCopyInto(out *EnforcementPointStatus) {
	_ = "STUB: not implemented"

	// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnforcementPointStatus.
	return
}

func (in *EnforcementPointStatus) DeepCopy() *EnforcementPointStatus {
	_ = "STUB: not implemented"
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Error) DeepCopyInto(out *Error) {
	_ = "STUB: not implemented"

	// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Error.
	return
}

func (in *Error) DeepCopy() *Error { _ = "STUB: not implemented"; return nil }

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExpansionTemplateError) DeepCopyInto(out *ExpansionTemplateError) {
	_ = "STUB: not implemented"

	// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExpansionTemplateError.
	return
}

func (in *ExpansionTemplateError) DeepCopy() *ExpansionTemplateError {
	_ = "STUB: not implemented"
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExpansionTemplatePodStatus) DeepCopyInto(out *ExpansionTemplatePodStatus) {
	_ = "STUB: not implemented"
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExpansionTemplatePodStatus.
func (in *ExpansionTemplatePodStatus) DeepCopy() *ExpansionTemplatePodStatus {
	_ = "STUB: not implemented"
	return nil
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ExpansionTemplatePodStatus) DeepCopyObject() runtime.Object {
	_ = "STUB: not implemented"
	return *new(runtime.Object)
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExpansionTemplatePodStatusList) DeepCopyInto(out *ExpansionTemplatePodStatusList) {
	_ = "STUB: not implemented"
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExpansionTemplatePodStatusList.
func (in *ExpansionTemplatePodStatusList) DeepCopy() *ExpansionTemplatePodStatusList {
	_ = "STUB: not implemented"
	return nil
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ExpansionTemplatePodStatusList) DeepCopyObject() runtime.Object {
	_ = "STUB: not implemented"
	return *new(runtime.Object)
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExpansionTemplatePodStatusStatus) DeepCopyInto(out *ExpansionTemplatePodStatusStatus) {
	_ = "STUB: not implemented"
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExpansionTemplatePodStatusStatus.
func (in *ExpansionTemplatePodStatusStatus) DeepCopy() *ExpansionTemplatePodStatusStatus {
	_ = "STUB: not implemented"
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MutatorError) DeepCopyInto(out *MutatorError) {
	_ = "STUB: not implemented"

	// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MutatorError.
	return
}

func (in *MutatorError) DeepCopy() *MutatorError { _ = "STUB: not implemented"; return nil }

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MutatorPodStatus) DeepCopyInto(out *MutatorPodStatus) { _ = "STUB: not implemented"; return }

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MutatorPodStatus.
func (in *MutatorPodStatus) DeepCopy() *MutatorPodStatus { _ = "STUB: not implemented"; return nil }

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MutatorPodStatus) DeepCopyObject() runtime.Object {
	_ = "STUB: not implemented"
	return *new(runtime.Object)
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MutatorPodStatusList) DeepCopyInto(out *MutatorPodStatusList) {
	_ = "STUB: not implemented"
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MutatorPodStatusList.
func (in *MutatorPodStatusList) DeepCopy() *MutatorPodStatusList {
	_ = "STUB: not implemented"
	return nil
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MutatorPodStatusList) DeepCopyObject() runtime.Object {
	_ = "STUB: not implemented"
	return *new(runtime.Object)
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MutatorPodStatusStatus) DeepCopyInto(out *MutatorPodStatusStatus) {
	_ = "STUB: not implemented"
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MutatorPodStatusStatus.
func (in *MutatorPodStatusStatus) DeepCopy() *MutatorPodStatusStatus {
	_ = "STUB: not implemented"
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderError) DeepCopyInto(out *ProviderError) { _ = "STUB: not implemented"; return }

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderError.
func (in *ProviderError) DeepCopy() *ProviderError { _ = "STUB: not implemented"; return nil }

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderPodStatus) DeepCopyInto(out *ProviderPodStatus) {
	_ = "STUB: not implemented"
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderPodStatus.
func (in *ProviderPodStatus) DeepCopy() *ProviderPodStatus { _ = "STUB: not implemented"; return nil }

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProviderPodStatus) DeepCopyObject() runtime.Object {
	_ = "STUB: not implemented"
	return *new(runtime.Object)
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderPodStatusList) DeepCopyInto(out *ProviderPodStatusList) {
	_ = "STUB: not implemented"
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderPodStatusList.
func (in *ProviderPodStatusList) DeepCopy() *ProviderPodStatusList {
	_ = "STUB: not implemented"
	return nil
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProviderPodStatusList) DeepCopyObject() runtime.Object {
	_ = "STUB: not implemented"
	return *new(runtime.Object)
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderPodStatusStatus) DeepCopyInto(out *ProviderPodStatusStatus) {
	_ = "STUB: not implemented"
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderPodStatusStatus.
func (in *ProviderPodStatusStatus) DeepCopy() *ProviderPodStatusStatus {
	_ = "STUB: not implemented"
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VAPGenerationStatus) DeepCopyInto(out *VAPGenerationStatus) {
	_ = "STUB: not implemented"

	// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VAPGenerationStatus.
	return
}

func (in *VAPGenerationStatus) DeepCopy() *VAPGenerationStatus {
	_ = "STUB: not implemented"
	return nil
}
