//go:build !ignore_autogenerated

/*

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExpansionTemplate) DeepCopyInto(out *ExpansionTemplate) {
	_ = "STUB: not implemented"
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExpansionTemplate.
func (in *ExpansionTemplate) DeepCopy() *ExpansionTemplate { _ = "STUB: not implemented"; return nil }

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ExpansionTemplate) DeepCopyObject() runtime.Object {
	_ = "STUB: not implemented"
	return *new(runtime.Object)
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExpansionTemplateList) DeepCopyInto(out *ExpansionTemplateList) {
	_ = "STUB: not implemented"
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExpansionTemplateList.
func (in *ExpansionTemplateList) DeepCopy() *ExpansionTemplateList {
	_ = "STUB: not implemented"
	return nil
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ExpansionTemplateList) DeepCopyObject() runtime.Object {
	_ = "STUB: not implemented"
	return *new(runtime.Object)
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExpansionTemplateSpec) DeepCopyInto(out *ExpansionTemplateSpec) {
	_ = "STUB: not implemented"
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExpansionTemplateSpec.
func (in *ExpansionTemplateSpec) DeepCopy() *ExpansionTemplateSpec {
	_ = "STUB: not implemented"
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExpansionTemplateStatus) DeepCopyInto(out *ExpansionTemplateStatus) {
	_ = "STUB: not implemented"
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExpansionTemplateStatus.
func (in *ExpansionTemplateStatus) DeepCopy() *ExpansionTemplateStatus {
	_ = "STUB: not implemented"
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GeneratedGVK) DeepCopyInto(out *GeneratedGVK) {
	_ = "STUB: not implemented"

	// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GeneratedGVK.
	return
}

func (in *GeneratedGVK) DeepCopy() *GeneratedGVK { _ = "STUB: not implemented"; return nil }
