//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by conversion-gen. DO NOT EDIT.

package v1beta1

import (
	unversioned "github.com/open-policy-agent/gatekeeper/v3/apis/expansion/unversioned"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error { _ = "STUB: not implemented"; return nil }

func autoConvert_v1beta1_ExpansionTemplate_To_unversioned_ExpansionTemplate(in *ExpansionTemplate, out *unversioned.ExpansionTemplate, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

// Convert_v1beta1_ExpansionTemplate_To_unversioned_ExpansionTemplate is an autogenerated conversion function.
func Convert_v1beta1_ExpansionTemplate_To_unversioned_ExpansionTemplate(in *ExpansionTemplate, out *unversioned.ExpansionTemplate, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

func autoConvert_unversioned_ExpansionTemplate_To_v1beta1_ExpansionTemplate(in *unversioned.ExpansionTemplate, out *ExpansionTemplate, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

// Convert_unversioned_ExpansionTemplate_To_v1beta1_ExpansionTemplate is an autogenerated conversion function.
func Convert_unversioned_ExpansionTemplate_To_v1beta1_ExpansionTemplate(in *unversioned.ExpansionTemplate, out *ExpansionTemplate, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

func autoConvert_v1beta1_ExpansionTemplateList_To_unversioned_ExpansionTemplateList(in *ExpansionTemplateList, out *unversioned.ExpansionTemplateList, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

// Convert_v1beta1_ExpansionTemplateList_To_unversioned_ExpansionTemplateList is an autogenerated conversion function.
func Convert_v1beta1_ExpansionTemplateList_To_unversioned_ExpansionTemplateList(in *ExpansionTemplateList, out *unversioned.ExpansionTemplateList, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

func autoConvert_unversioned_ExpansionTemplateList_To_v1beta1_ExpansionTemplateList(in *unversioned.ExpansionTemplateList, out *ExpansionTemplateList, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

// Convert_unversioned_ExpansionTemplateList_To_v1beta1_ExpansionTemplateList is an autogenerated conversion function.
func Convert_unversioned_ExpansionTemplateList_To_v1beta1_ExpansionTemplateList(in *unversioned.ExpansionTemplateList, out *ExpansionTemplateList, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

func autoConvert_v1beta1_ExpansionTemplateSpec_To_unversioned_ExpansionTemplateSpec(in *ExpansionTemplateSpec, out *unversioned.ExpansionTemplateSpec, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

// Convert_v1beta1_ExpansionTemplateSpec_To_unversioned_ExpansionTemplateSpec is an autogenerated conversion function.
func Convert_v1beta1_ExpansionTemplateSpec_To_unversioned_ExpansionTemplateSpec(in *ExpansionTemplateSpec, out *unversioned.ExpansionTemplateSpec, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

func autoConvert_unversioned_ExpansionTemplateSpec_To_v1beta1_ExpansionTemplateSpec(in *unversioned.ExpansionTemplateSpec, out *ExpansionTemplateSpec, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

// Convert_unversioned_ExpansionTemplateSpec_To_v1beta1_ExpansionTemplateSpec is an autogenerated conversion function.
func Convert_unversioned_ExpansionTemplateSpec_To_v1beta1_ExpansionTemplateSpec(in *unversioned.ExpansionTemplateSpec, out *ExpansionTemplateSpec, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

func autoConvert_v1beta1_ExpansionTemplateStatus_To_unversioned_ExpansionTemplateStatus(in *ExpansionTemplateStatus, out *unversioned.ExpansionTemplateStatus, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

// Convert_v1beta1_ExpansionTemplateStatus_To_unversioned_ExpansionTemplateStatus is an autogenerated conversion function.
func Convert_v1beta1_ExpansionTemplateStatus_To_unversioned_ExpansionTemplateStatus(in *ExpansionTemplateStatus, out *unversioned.ExpansionTemplateStatus, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

func autoConvert_unversioned_ExpansionTemplateStatus_To_v1beta1_ExpansionTemplateStatus(in *unversioned.ExpansionTemplateStatus, out *ExpansionTemplateStatus, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

// Convert_unversioned_ExpansionTemplateStatus_To_v1beta1_ExpansionTemplateStatus is an autogenerated conversion function.
func Convert_unversioned_ExpansionTemplateStatus_To_v1beta1_ExpansionTemplateStatus(in *unversioned.ExpansionTemplateStatus, out *ExpansionTemplateStatus, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

func autoConvert_v1beta1_GeneratedGVK_To_unversioned_GeneratedGVK(in *GeneratedGVK, out *unversioned.GeneratedGVK, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

// Convert_v1beta1_GeneratedGVK_To_unversioned_GeneratedGVK is an autogenerated conversion function.
func Convert_v1beta1_GeneratedGVK_To_unversioned_GeneratedGVK(in *GeneratedGVK, out *unversioned.GeneratedGVK, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

func autoConvert_unversioned_GeneratedGVK_To_v1beta1_GeneratedGVK(in *unversioned.GeneratedGVK, out *GeneratedGVK, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}

// Convert_unversioned_GeneratedGVK_To_v1beta1_GeneratedGVK is an autogenerated conversion function.
func Convert_unversioned_GeneratedGVK_To_v1beta1_GeneratedGVK(in *unversioned.GeneratedGVK, out *GeneratedGVK, s conversion.Scope) error {
	_ = "STUB: not implemented"
	return nil
}
